modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "dyenamics"
version = "2.0.0"
displayName = "Dyenamics"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team Cough on Five Horses"
authors = "Hekera, LobsterJonn, Reda, Cait"
description = '''
Minecraft gets dyenamic!
Contains various pigment options for colorful gameplay!
'''
[[dependencies.dyenamics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "AFTER"
side = "BOTH"
