modLoader = "javafml"
loaderVersion = "[35,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_dyenamics"
version = "1.0.0"
displayName = "Thermal Dyenamics"
displayURL = "https://teamcofh.com/"
logoFile = "logo.png"
credits = "Team Cough on Five Horses"
authors = "Hekera, Reda"
description = '''
Thermal gets dyenamic!
Contains various pigment options for colorful gameplay!
'''
[[dependencies.thermal_dyenamics]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "AFTER"
side = "BOTH"
